import Foundation

// MARK: - ChatMessage

/// Unified model representing any item rendered in the chat thread.
public enum ChatMessage: Identifiable, Equatable {

    /// A message sent by the user (text, optionally with an image or audio).
    case userMessage(
        id: String,
        text: String,
        imageUrl: URL?,
        audioUrl: URL?
    )

    /// A response generated by the AI.
    case aiResponse(
        id: String,
        text: String,
        followUpQuestions: [String]?,
        isPreGenerated: Bool,
        messageId: String?
    )

    /// Transient placeholder shown while waiting for the AI response.
    case loadingPlaceholder(id: String)

    // MARK: Identifiable

    public var id: String {
        switch self {
        case .userMessage(let id, _, _, _):
            return id
        case .aiResponse(let id, _, _, _, _):
            return id
        case .loadingPlaceholder(let id):
            return id
        }
    }

    // MARK: Equatable

    public static func == (lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        switch (lhs, rhs) {
        case (
            .userMessage(let lid, let lt, let liu, let lau),
            .userMessage(let rid, let rt, let riu, let rau)
        ):
            return lid == rid && lt == rt && liu == riu && lau == rau

        case (
            .aiResponse(let lid, let lt, let lfq, let lip, let lmid),
            .aiResponse(let rid, let rt, let rfq, let rip, let rmid)
        ):
            return lid == rid && lt == rt && lfq == rfq && lip == rip && lmid == rmid

        case (.loadingPlaceholder(let lid), .loadingPlaceholder(let rid)):
            return lid == rid

        default:
            return false
        }
    }

    // MARK: Convenience Helpers

    /// Returns the AI response text, if this is an aiResponse case.
    public var aiResponseText: String? {
        if case .aiResponse(_, let text, _, _, _) = self { return text }
        return nil
    }

    /// Returns the messageId from an aiResponse, used for audio synthesis.
    public var aiMessageId: String? {
        if case .aiResponse(_, _, _, _, let mid) = self { return mid }
        return nil
    }

    /// Returns true if this is the loading placeholder.
    public var isLoading: Bool {
        if case .loadingPlaceholder = self { return true }
        return false
    }

    /// Returns true if this is a pre-generated AI response.
    public var isPreGenerated: Bool {
        if case .aiResponse(_, _, _, let pre, _) = self { return pre }
        return false
    }

    /// Returns true if this is an AI response (any variant).
    public var isAiResponse: Bool {
        if case .aiResponse = self { return true }
        return false
    }

    /// Returns the follow-up questions attached to this AI response, if any.
    public var aiFollowUpQuestions: [String]? {
        if case .aiResponse(_, _, let fqs, _, _) = self { return fqs }
        return nil
    }

    /// Returns a copy of this aiResponse with the given follow-up questions set.
    /// Returns self unchanged for non-aiResponse cases.
    public func withFollowUpQuestions(_ questions: [String]?) -> ChatMessage {
        guard case .aiResponse(let id, let text, _, let pregen, let mid) = self else { return self }
        return .aiResponse(id: id, text: text, followUpQuestions: questions, isPreGenerated: pregen, messageId: mid)
    }
}
